[build]
  command = "rm -rf node_modules package-lock.json && npm install --verbose && npm install typescript@5.3.3 --save-dev --verbose && npx tsc --skipLibCheck --noEmit --verbose && vite build --mode production --debug"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  VITE_SKIP_TS_CHECK = "true"
  NODE_ENV = "production"
  CI = "true"
  DEBUG = "*"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NODE_OPTIONS = "--trace-warnings"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 