[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  VITE_SKIP_TS_CHECK = "true"
  NODE_ENV = "production"
  CI = "true"
  DEBUG = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 