[build]
  command = "npm install --verbose && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  CI = "true"
  DEBUG = "*"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NODE_OPTIONS = "--trace-warnings"
  VITE_DEBUG = "true"
  VITE_LOG_LEVEL = "info"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 