[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  VITE_SKIP_TS_CHECK = "true"
  NODE_ENV = "production"
  CI = "true"
  DEBUG = "*"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NODE_OPTIONS = "--trace-warnings --max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 