[build]
  command = "npm install --force && npm install react-day-picker@8.10.0 && vite build --debug"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  DEBUG = "*"
  CI = "true"
  VITE_SKIP_TS_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 