[build]
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install typescript@5.3.3 --save-dev --verbose && npm install --verbose --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  VITE_SKIP_TS_CHECK = "true"
  NODE_ENV = "production"
  CI = "true"
  DEBUG = "*"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NODE_OPTIONS = "--trace-warnings --max-old-space-size=4096"
  FORCE_COLOR = "true"
  NODE_DEBUG = "*"
  NODE_PATH = "./node_modules"
  VITE_BASE_URL = "/"
  VITE_ALIAS = "#"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_NO_WARNINGS = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 